name:
  cvxpy
channels:
  - base
  - conda-forge
dependencies:
  - python=3.7.8 
  - numpy=1.19.0
  - scipy=1.5.2
  - pandas=1.1.2
  - matplotlib=3.3.1
  - seaborn=0.11.0   # better color schemes for 3d plots
  - jupyterlab=2.2.8
  - ipykernel
  - cvxpy=1.1